<a href="https://colab.research.google.com/github/Matajur/data/blob/main/data_hw_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import numpy as np

A = 1
B = A + 10
C = A + 100
D = A + 50

task 01

In [18]:
a = np.arange(A, B)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


task 02

In [19]:
b = np.zeros((3,3), dtype=int)
print(b)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


task 03

In [20]:
c = np.random.randint(A, B, size=(5, 5))
print(c)

[[6 2 6 2 6]
 [7 5 6 9 5]
 [1 2 9 8 7]
 [8 7 6 7 9]
 [9 2 4 9 1]]


task 04

In [21]:
d = np.random.random((4, 4))
print(d)

[[0.11161147 0.28135187 0.53740465 0.56135322]
 [0.94740621 0.35027871 0.26494967 0.01224442]
 [0.87075192 0.27093288 0.74094758 0.31877786]
 [0.02094567 0.31811131 0.25566814 0.4443395 ]]


task 05

In [22]:
e = np.random.randint(A, B, size=5)
f = np.random.randint(A, B, size=5)
print(e, f)
print(e + f)
print(e - f)
print(e * f)

[4 8 3 5 8] [7 2 5 7 3]
[11 10  8 12 11]
[-3  6 -2 -2  5]
[28 16 15 35 24]


task 06

In [23]:
g = np.random.randint(A, B, size=7)
h = np.random.randint(A, B, size=7)
print(g, h)
print(np.dot(g, h))

[6 8 6 1 2 9 7] [ 3  7 10  6  9  7 10]
291


task 07

In [24]:
i = np.random.randint(A, B, size=(2, 2))
j = np.random.randint(A, B, size=(2, 3))
print(i, j)
print(i.shape, j.shape) # (2, 2) (2, 3)
print(i.size, j.size) # 4 6
print(np.dot(i, j))

[[1 2]
 [6 8]] [[7 7 9]
 [8 6 4]]
(2, 2) (2, 3)
4 6
[[ 23  19  17]
 [106  90  86]]


task 08

In [25]:
k = np.random.randint(A, B, size=(3, 3))
print(k)
print(np.linalg.inv(k))

[[ 7  1  5]
 [ 5  2 10]
 [ 7  4  1]]
[[ 2.22222222e-01 -1.11111111e-01  7.93016446e-18]
 [-3.80116959e-01  1.63742690e-01  2.63157895e-01]
 [-3.50877193e-02  1.22807018e-01 -5.26315789e-02]]


task 09

In [26]:
l = np.random.random((4, 4))
print(l)
print(l.T)

[[0.29027475 0.89594458 0.41664094 0.77222053]
 [0.13292569 0.48609751 0.06308044 0.66618923]
 [0.62068019 0.59308101 0.81288847 0.57548024]
 [0.97802642 0.39675247 0.66967219 0.40633293]]
[[0.29027475 0.13292569 0.62068019 0.97802642]
 [0.89594458 0.48609751 0.59308101 0.39675247]
 [0.41664094 0.06308044 0.81288847 0.66967219]
 [0.77222053 0.66618923 0.57548024 0.40633293]]


task 10

In [27]:
m = np.random.randint(A, B, size=(3, 4))
n = np.random.randint(A, B, size=4)
print(m, n)
print(m.shape, n.shape) # (2, 4) (4,)
print(m.size, n.size) # 12 4
print(np.dot(m, n))

[[10  1  8  9]
 [ 8  4  3 10]
 [ 3  9 10  6]] [5 9 1 4]
(3, 4) (4,)
12 4
[103 119 130]


task 11

In [28]:
o = np.random.random((2, 3))
p = np.random.random((3, 1))
print(o, p)
print(o.shape, p.shape) # (2, 3) (3, 1)
print(o.size, p.size) # 6 3
print(np.dot(o, p))

[[0.9760252  0.14184384 0.65728396]
 [0.66638134 0.54483415 0.87904792]] [[0.74524039]
 [0.56205619]
 [0.94087499]]
(2, 3) (3, 1)
6 3
[[1.42551966]
 [1.6299159 ]]


task 12

In [29]:
q = np.random.randint(A, B, size=(2, 2))
r = np.random.randint(A, B, size=(2, 2))
print(q, r)
print(q * r)

[[1 4]
 [5 4]] [[9 5]
 [1 7]]
[[ 9 20]
 [ 5 28]]


task 13

In [30]:
s = np.random.randint(A, B, size=(2, 2))
t = np.random.randint(A, B, size=(2, 2))
print(s, t)
print(np.dot(s, t))

[[3 5]
 [1 2]] [[ 3  7]
 [ 3 10]]
[[24 71]
 [ 9 27]]


task 14

In [31]:
u = np.random.randint(A, C, size=(5, 5))
print(u)
print(u.sum())

[[53 23 99 15 56]
 [ 9 22 54 50 77]
 [92 91 77 42 14]
 [64 93 51 20 34]
 [68 56 49 89 91]]
1389


task 15

In [32]:
v = np.random.randint(A, B, size=(4, 4))
w = np.random.randint(A, B, size=(4, 4))
print(v, w)
print(v - w)

[[10  2  5 10]
 [ 8  4  6  9]
 [ 2 10  1  8]
 [ 4  8  5  2]] [[10  8  5  7]
 [ 3  6 10  6]
 [ 6 10  7  7]
 [ 9  2  7 10]]
[[ 0 -6  0  3]
 [ 5 -2 -4  3]
 [-4  0 -6  1]
 [-5  6 -2 -8]]


task 16

In [33]:
x = np.random.random((3, 3))
y = np.ones((3, 1), dtype=int)
print(x, y)
print(np.dot(x, y))

[[0.36527417 0.88631701 0.29432809]
 [0.4932445  0.03302464 0.40588457]
 [0.6000137  0.36251808 0.61691985]] [[1]
 [1]
 [1]]
[[1.54591927]
 [0.93215371]
 [1.57945162]]


task 17

In [5]:
z = np.random.randint(A, B, size=(4, 3))
print(z)
print(z**2)

[[10  2  5]
 [ 9  6  9]
 [ 3  1  2]
 [ 5  6  2]]
[[100   4  25]
 [ 81  36  81]
 [  9   1   4]
 [ 25  36   4]]


task 18

In [4]:
zz = np.random.randint(A, D, size=4)
print(zz)
print(np.sqrt(zz))

[42 13 47 15]
[6.4807407  3.60555128 6.8556546  3.87298335]
