<a href="https://colab.research.google.com/github/Matajur/data/blob/main/data_hw_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [89]:
import numpy as np

A = 1
B = A + 10
C = A + 100
D = A + 50

In [100]:
# task 01
a = np.arange(A, B)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [8]:
# task 02
b = np.zeros((3,3), dtype=int)
print(b)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [99]:
# task 03
c = np.random.randint(A, B, size=(5, 5))
print(c)

[[ 9 10  6  3  8]
 [ 1  2  7  7  9]
 [ 9  5  3  8 10]
 [10  3 10  6  1]
 [ 7  5  3  8  8]]


In [17]:
# task 04
d = np.random.random((4, 4))
print(d)

[[0.77184038 0.34989376 0.42992279 0.26349764]
 [0.72807326 0.16666397 0.70781741 0.26986698]
 [0.8998674  0.66122584 0.21002984 0.78171485]
 [0.63254402 0.62674144 0.88541952 0.25010956]]


In [98]:
# task 05
e = np.random.randint(A, B, size=5)
f = np.random.randint(A, B, size=5)
print(e, f)
print(e + f)
print(e - f)
print(e * f)

[1 6 1 7 6] [8 3 1 9 8]
[ 9  9  2 16 14]
[-7  3  0 -2 -2]
[ 8 18  1 63 48]


In [97]:
# task 06
g = np.random.randint(A, B, size=7)
h = np.random.randint(A, B, size=7)
print(g, h)
print(np.dot(g, h))

[9 7 2 6 9 2 9] [ 6  2  8 10  6  8  7]
277


In [96]:
# task 07
i = np.random.randint(A, B, size=(2, 2))
j = np.random.randint(A, B, size=(2, 3))
print(i, j)
print(i.shape, j.shape) # (2, 2) (2, 3)
print(i.size, j.size) # 4 6
print(np.dot(i, j))

[[ 2 10]
 [ 4  6]] [[8 5 6]
 [9 6 3]]
(2, 2) (2, 3)
4 6
[[106  70  42]
 [ 86  56  42]]


In [95]:
# task 08
k = np.random.randint(A, B, size=(3, 3))
print(k)
print(np.linalg.inv(k))

[[10  5  2]
 [ 9  4  2]
 [ 8  4  8]]
[[-0.75     1.      -0.0625 ]
 [ 1.75    -2.       0.0625 ]
 [-0.125    0.       0.15625]]


In [46]:
# task 09
l = np.random.random((4, 4))
print(l)
print(l.T)

[[0.54572621 0.50542249 0.66434084 0.05047001]
 [0.6477022  0.60814061 0.00418285 0.04503934]
 [0.69105839 0.18921988 0.03844949 0.90052799]
 [0.92382955 0.30233355 0.27141856 0.50877745]]
[[0.54572621 0.6477022  0.69105839 0.92382955]
 [0.50542249 0.60814061 0.18921988 0.30233355]
 [0.66434084 0.00418285 0.03844949 0.27141856]
 [0.05047001 0.04503934 0.90052799 0.50877745]]


In [94]:
# task 10
m = np.random.randint(A, B, size=(3, 4))
n = np.random.randint(A, B, size=4)
print(m, n)
print(m.shape, n.shape) # (2, 4) (4,)
print(m.size, n.size) # 12 4
print(np.dot(m, n))

[[ 9  8  7 10]
 [ 2  4  9  8]
 [ 2  5  4  8]] [2 5 5 2]
(3, 4) (4,)
12 4
[113  85  65]


In [93]:
# task 11
o = np.random.random((2, 3))
p = np.random.random(3)
print(o, p)
print(o.shape, p.shape) # (2, 3) (3,)
print(o.size, p.size) # 6 3
print(np.dot(o, p))

[[0.96613127 0.34623442 0.32146322]
 [0.68195021 0.33505788 0.68849042]] [0.16678609 0.96946709 0.12998621]
(2, 3) (3,)
6 3
[0.53858593 0.52806166]


In [92]:
# task 12
q = np.random.randint(A, B, size=(2, 2))
r = np.random.randint(A, B, size=(2, 2))
print(q, r)
print(q * r)

[[3 4]
 [6 7]] [[5 8]
 [6 9]]
[[15 32]
 [36 63]]


In [91]:
# task 13
s = np.random.randint(A, B, size=(2, 2))
t = np.random.randint(A, B, size=(2, 2))
print(s, t)
print(np.dot(s, t))

[[ 2 10]
 [ 6  7]] [[ 6 10]
 [ 4  9]]
[[ 52 110]
 [ 64 123]]


In [90]:
# task 14
u = np.random.randint(A, C, size=(5, 5))
print(u)
print(u.sum())

[[ 5 58 87 93 80]
 [91 11 34 11 31]
 [25 61 45 11 95]
 [14 86 56 13 79]
 [75 21 55 26 28]]
1191


In [62]:
# task 15
v = np.random.randint(A, B, size=(4, 4))
w = np.random.randint(A, B, size=(4, 4))
print(v, w)
print(v - w)

[[10 10  2  3]
 [ 8  1  3  6]
 [ 8  1  4  4]
 [ 9  7  2  6]] [[4 9 3 2]
 [3 7 6 2]
 [2 4 4 9]
 [8 7 4 2]]
[[ 6  1 -1  1]
 [ 5 -6 -3  4]
 [ 6 -3  0 -5]
 [ 1  0 -2  4]]


In [70]:
# task 16
x = np.random.random((3, 3))
y = np.ones((3, 1), dtype=int)
print(x, y)
print(np.dot(x, y))

[[0.90145859 0.92406561 0.49161879]
 [0.23583996 0.06872232 0.39819645]
 [0.01121652 0.0452122  0.19087865]] [[1]
 [1]
 [1]]
[[2.31714299]
 [0.70275872]
 [0.24730736]]


In [71]:
# task 17
z = np.random.randint(A, B, size=(3, 4))
print(z)
print(z**2)

[[9 2 9 4]
 [3 3 3 4]
 [7 5 9 9]]
[[81  4 81 16]
 [ 9  9  9 16]
 [49 25 81 81]]


In [88]:
# task 18
zz = np.random.randint(A, D, size=(4, 1))
print(zz)
print(zz**0.5)

[[37]
 [15]
 [31]
 [ 8]]
[[6.08276253]
 [3.87298335]
 [5.56776436]
 [2.82842712]]
